#!/bin/bash -e

# 00-prerun.sh ========================

FROM_ROOTFS raspbian/lite

# 10-chromium-mods.debconf ========================

ON_CHROOT debconf-set-selections <10-chromium-mods.debconf

# 15-desktop.packages-nr ========================

ON_CHROOT apt-get install -y --no-install-recommends                \
    xserver-xorg-video-fbdev xserver-xorg xinit                     \
    xserver-xorg-video-fbturbo mousepad lxde lxtask menu-xdg zenity \
    xdg-utils gvfs-backends gvfs-fuse lightdm                       \
    gnome-themes-standard-data gnome-icon-theme

# 20-desktop-ext.packages ========================

ON_CHROOT apt-get install -y    gstreamer1.0-x gstreamer1.0-omx     \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good             \
    gstreamer1.0-plugins-bad gstreamer1.0-alsa gstreamer1.0-libav   \
    qpdfview gtk2-engines alsa-utils desktop-base git omxplayer     \
    raspberrypi-artwork policykit-1 gvfs rfkill chromium-browser    \
    rpi-chromium-mods gldriver-test fonts-droid-fallback            \
    fonts-liberation2 obconf arandr

# 25-desktop-ext.sh ========================

ON_CHROOT << EOF
update-alternatives --install /usr/bin/x-www-browser \
  x-www-browser /usr/bin/chromium-browser 86
update-alternatives --install /usr/bin/gnome-www-browser \
  gnome-www-browser /usr/bin/chromium-browser 86
EOF

# 30-tweaks.sh ========================

rm -f "${ROOTFS_DIR}/etc/systemd/system/dhcpcd.service.d/wait.conf"
