#!/bin/bash

DIST_STR=raspbian-buster
DEST_DIR=${ROOTFS_DIR}

if [[ -d "${DEST_DIR}" ]]; then
    exit 0;
fi

if [[ "${DIST_STR%%-*}" == "raspbian" ]]; then
    RASPBIAN_VERSION="${DIST_STR#*-}"
    BOOTSTRAP_CMD=debootstrap
    BOOTSTRAP_ARGS=()

    export http_proxy=${APT_PROXY}

    if [ "$(setarch linux32 uname -m)" == "i686" ]; then
        if ! grep flags /proc/sys/fs/binfmt_misc/qemu-arm | grep F >/dev/null; then
            BOOTSTRAP_CMD=qemu-debootstrap
        fi
    fi

    BOOTSTRAP_ARGS+=(--arch armhf)
    BOOTSTRAP_ARGS+=(--components "main,contrib,non-free")
    BOOTSTRAP_ARGS+=(--keyring "${BASH_SOURCE%/*}/raspberrypi.gpg")
    BOOTSTRAP_ARGS+=("${RASPBIAN_VERSION}")
    BOOTSTRAP_ARGS+=("${DEST_DIR}")
    BOOTSTRAP_ARGS+=(http://raspbian.raspberrypi.org/raspbian/)
    printf -v BOOTSTRAP_STR '%q ' "${BOOTSTRAP_ARGS[@]}"

    pwd
    setarch linux32 capsh --drop=cap_setfcap -- -c "'${BOOTSTRAP_CMD}' $BOOTSTRAP_STR" || true

    if [ -d "$2/debootstrap" ]; then
        rmdir "$2/debootstrap"
    fi
else
    echo "Unknown distribution ${DIST_STR}"
    exit 1
fi
