#!/bin/bash

BOOTSTRAP_CMD=debootstrap
BOOTSTRAP_ARGS=()

export http_proxy=${APT_PROXY}

if [ "$(setarch linux32 uname -m)" == "i686" ]; then
    if ! grep flags /proc/sys/fs/binfmt_misc/qemu-arm | grep F >/dev/null; then
        BOOTSTRAP_CMD=qemu-debootstrap
    fi
fi

BOOTSTRAP_ARGS+=(--arch armhf)
BOOTSTRAP_ARGS+=(--components "main,contrib,non-free")
BOOTSTRAP_ARGS+=(--keyring "${FILES}/raspberrypi.gpg")
BOOTSTRAP_ARGS+=("$@")
printf -v BOOTSTRAP_STR '%q ' "${BOOTSTRAP_ARGS[@]}"

setarch linux32 capsh --drop=cap_setfcap -- -c "'${BOOTSTRAP_CMD}' $BOOTSTRAP_STR" || true

if [ -d "$2/debootstrap" ]; then
    rmdir "$2/debootstrap"
fi
